<a href="https://colab.research.google.com/github/Naveenkumarwebknot/AI-ML/blob/main/Feature_Engineering(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("./vgsales.csv")

In [3]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

**Check the total number and percentage of missing values per column in the dataset**

In [4]:
missing_value=df.isnull().sum()
missing_value

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [5]:
percentage_missing = (missing_value / len(df)) * 100
percentage_missing

Rank            0.000000
Name            0.000000
Platform        0.000000
Year            1.632727
Genre           0.000000
Publisher       0.349440
NA_Sales        0.000000
EU_Sales        0.000000
JP_Sales        0.000000
Other_Sales     0.000000
Global_Sales    0.000000
dtype: float64

**Exclude all cases (listwise) with missing values**

In [6]:
df_droped = df.dropna()
df_droped

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

**Create an additional column ‘NA’ indicating whether the data was missing for that observation**

In [7]:
df1=df.copy(False)
df1['NA'] = df1.isnull().any(axis=1).astype(int)
df1

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,NA
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,0
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0

**Arbitrary Value Imputation - replace the NA by arbitrary values**

In [8]:
df1.fillna(99)
df1

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,NA
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,0
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0

**Mean/Median/Mode Imputation - replace the NA be mean/median/mode of that column**

In [9]:

df1_mean=df1.mean()
df1_filled_mean = df1.fillna(df1_mean)

df1

<ipython-input-9-062bb83a0918>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1_mean=df1.mean()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,NA
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,0
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0

End of distribution Imputation - replace the NA by values that are at the far end of the distribution of that column (tip - consider it as Normal Distribution -> 3*std away from the mean) **bold text**

In [10]:
df2=df.copy()
end_of_distribution=df2.mean()+3*df2.std()
df2.fillna(end_of_distribution)

<ipython-input-10-ba99c72ef91b>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  end_of_distribution=df2.mean()+3*df2.std()
<ipython-input-10-ba99c72ef91b>:2: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  end_of_distribution=df2.mean()+3*df2.std()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

**Random Imputation - Replace the NA with random sampling from the pool of available observation of the column**

In [12]:
df3=df.copy()
for col in df3.columns:
    missing = df3[col].isnull()
    num_missing = missing.sum()
    if num_missing > 0:
        values = df3.loc[~missing, col]
        rand_index = np.random.choice(values.index, size=num_missing)
        df3.loc[missing, col] = values[rand_index].values
df3

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

**Identify outliers based on arbitrary boundaries**

In [13]:
numeric_cols = df2.select_dtypes(include=np.number)
lower=0
upper=5000
outliers = numeric_cols[(numeric_cols < lower) | (numeric_cols > upper)].any(axis=1)
outliers

0        False
1        False
2        False
3        False
4        False
         ...
16593     True
16594     True
16595     True
16596     True
16597     True
Length: 16598, dtype: bool

**Identify outliers by IQR - Interquartile Range Rule**

In [14]:
numeric_cols = df2.select_dtypes(include=np.number)
Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)
IQR = Q3 - Q1
outliers = ((numeric_cols < (Q1 - 1.5 * IQR)) | (numeric_cols > (Q3 + 1.5 * IQR))).any(axis=1)
outliers

0         True
1         True
2         True
3         True
4         True
         ...
16593    False
16594    False
16595    False
16596    False
16597    False
Length: 16598, dtype: bool

Identify outliers by Mean and Standard Deviation

In [15]:
mean = df2.mean()
std_dev = df2.std()
lower = mean - 3 * std_dev
upper = mean + 3 * std_dev
outliers = ((df2 < lower) | (df > upper)).any(axis=1)
outliers

<ipython-input-15-0dfc825c039e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = df2.mean()
<ipython-input-15-0dfc825c039e>:2: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  std_dev = df2.std()
<ipython-input-15-0dfc825c039e>:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  outliers = ((df2 < lower) | (df > upper)).any(axis=1)

0         True
1         True
2         True
3         True
4         True
         ...
16593    False
16594    False
16595    False
16596    False
16597    False
Length: 16598, dtype: bool

**Impute outliers by arbitrary value**

In [16]:

df4=df2.copy()
numeric_cols = df4.select_dtypes(include=np.number)
Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)
IQR = Q3 - Q1
arbitrary_value = 999
outliers_replaced = numeric_cols.mask((numeric_cols < (Q1 - 1.5 * IQR)) | (numeric_cols > (Q3 + 1.5 * IQR)),arbitrary_value).any(axis=1)
numeric_cols[outliers_replaced]

        Rank    Year  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0          1  2006.0     41.49     29.02      3.77         8.46         82.74
1          2  1985.0     29.08      3.58      6.81         0.77         40.24
2          3  2008.0     15.85     12.88      3.79         3.31         35.82
3          4  2009.0     15.75     11.01      3.28         2.96         33.00
4          5  1996.0     11.27      8.89     10.22         1.00         31.37
...      ...     ...       ...       ...       ...          ...           ...
16593  16596  2002.0      0.01      0.00      0.00         0.00          0.01
16594  16597  2003.0      0.01      0.00      0.00         0.00          0.01
16595  16598  2008.0      0.00      0.00      0.00         0.00          0.01
16596  16599  2010.0      0.00      0.01      0.00         0.00          0.01
16597  16600  2003.0      0.01      0.00      0.00         0.00          0.01

[16598 rows x 7 columns]

**Winsorization - Top coding and bottom coding (capping the maximum of a distribution at an arbitrary set value, vice versa)**

In [17]:

from scipy.stats.mstats import winsorize
df5=df.copy()
numeric_cols = df5.select_dtypes(include=np.number)


winsorization_percentage = 0.05


df5_winsorized = numeric_cols.apply(lambda x: winsorize(x, limits=(winsorization_percentage, winsorization_percentage)))


df5_winsorized = pd.DataFrame(df5_winsorized, columns=df.columns)

df5_winsorized

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,831,NaN,NaN,2006.0,NaN,NaN,1.06,0.63,0.36,0.2,2.04
1,831,NaN,NaN,1996.0,NaN,NaN,1.06,0.63,0.36,0.2,2.04
2,831,NaN,NaN,2008.0,NaN,NaN,1.06,0.63,0.36,0.2,2.04
3,831,NaN,NaN,2009.0,NaN,NaN,1.06,0.63,0.36,0.2,2.04
4,831,NaN,NaN,1996.0,NaN,NaN,1.06,0.63,0.36,0.2,2.04
...,...,...,...,...,...,...,...,...,...,...,...
16593,15771,NaN,NaN,2002.0,NaN,NaN,0.01,0.00,0.00,0.0,0.02
16594,15771,NaN,NaN,2003.0,NaN,NaN,0.01,0.00,0.00,0.0,0.02
16595,15771,NaN,NaN,2008.0,NaN,NaN,0.00,0.00,0.00,0.0,0.02
16596,15771,NaN,NaN,2010.0,NaN,NaN,0.00,0.01,0.00,0.0,0.02
16597,15771,NaN,NaN,2003.0,NaN,NaN,0.01,0.00,0.00,0.0,0.02

Discard outliers

In [18]:
numeric_cols = df2.select_dtypes(include=np.number)
Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)
IQR = Q3 - Q1
outliers = ((numeric_cols < (Q1 - 1.5 * IQR)) | (numeric_cols > (Q3 + 1.5 * IQR))).any(axis=1)
df_cleaned = numeric_cols[~outliers]
df_cleaned

        Rank    Year  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
2206    2208  2009.0      0.51      0.26      0.09         0.08          0.94
2253    2255  2008.0      0.58      0.26      0.00         0.08          0.92
2278    2280  2008.0      0.58      0.24      0.01         0.09          0.91
2288    2290  2008.0      0.57      0.26      0.00         0.08          0.91
2330    2332  2001.0      0.60      0.22      0.05         0.02          0.89
...      ...     ...       ...       ...       ...          ...           ...
16593  16596  2002.0      0.01      0.00      0.00         0.00          0.01
16594  16597  2003.0      0.01      0.00      0.00         0.00          0.01
16595  16598  2008.0      0.00      0.00      0.00         0.00          0.01
16596  16599  2010.0      0.00      0.01      0.00         0.00          0.01
16597  16600  2003.0      0.01      0.00      0.00         0.00          0.01

[11926 rows x 7 columns]

In [19]:
numeric_cols = df2.select_dtypes(include=np.number)
Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)
IQR = Q3 - Q1
outliers = ((numeric_cols < (Q1 - 1.5 * IQR)) | (numeric_cols > (Q3 + 1.5 * IQR))).any(axis=1)
new_df=numeric_cols[outliers]
new_df['outliers']=outliers


for col in new_df:
  if new_df[col].dtype!='object':
    if new_df[col].dtype == 'float' or new_df[col].dtype == 'int':


        replacement_value = new_df[col].mean()







    new_df.loc[outliers, col] = replacement_value
new_df

<ipython-input-19-bf0f468c20f2>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['outliers']=outliers

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,outliers
0,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
1,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
2,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
3,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
4,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
...,...,...,...,...,...,...,...,...
14335,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
14507,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
14599,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
15867,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794
16073,3342.718964,2004.567129,0.685349,0.414563,0.249824,0.137121,1.486794,1.486794

**Normalisation - Standardization (Z-score scaling)**

In [23]:
from sklearn.preprocessing import StandardScaler

df6=df.copy()
scaler = StandardScaler()

df_numeric_scaled = pd.DataFrame(scaler.fit_transform(df6.select_dtypes(include=np.number)), columns=df6.select_dtypes(include=np.number).columns)
df_numeric_scaled

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,-1.732076,-0.069730,50.480508,57.136930,11.938058,44.606085,52.864025
1,-1.731867,-3.672528,35.284437,6.794188,21.767296,3.828224,25.532503
2,-1.731659,0.273393,19.084273,25.197785,12.002724,17.297115,22.690025
3,-1.731450,0.444955,18.961823,21.497277,10.353740,15.441165,20.876498
4,-1.731241,-1.785348,13.476053,17.302048,32.792857,5.047848,19.828254
...,...,...,...,...,...,...,...
16593,1.731197,-0.755977,-0.311841,-0.290207,-0.251492,-0.254864,-0.339194
16594,1.731406,-0.584416,-0.311841,-0.290207,-0.251492,-0.254864,-0.339194
16595,1.731615,0.273393,-0.324086,-0.290207,-0.251492,-0.254864,-0.339194
16596,1.731823,0.616517,-0.324086,-0.270418,-0.251492,-0.254864,-0.339194
16597,1.732032,-0.584416,-0.311841,-0.290207,-0.251492,-0.254864,-0.339194

**Min-Max scaling**

In [26]:
from sklearn.preprocessing import MinMaxScaler

df7=df.copy()
scaler = MinMaxScaler()


df_numeric_scaled = pd.DataFrame(scaler.fit_transform(df6.select_dtypes(include=np.number)), columns=df6.select_dtypes(include=np.number).columns)
df_numeric_scaled

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0.000000,0.650,1.000000,1.000000,0.368885,0.800378,1.000000
1,0.000060,0.125,0.700892,0.123363,0.666341,0.072848,0.486281
2,0.000120,0.700,0.382020,0.443832,0.370841,0.313150,0.432854
3,0.000181,0.725,0.379610,0.379394,0.320939,0.280038,0.398767
4,0.000241,0.400,0.271632,0.306340,1.000000,0.094607,0.379064
...,...,...,...,...,...,...,...
16593,0.999759,0.550,0.000241,0.000000,0.000000,0.000000,0.000000
16594,0.999819,0.575,0.000241,0.000000,0.000000,0.000000,0.000000
16595,0.999880,0.700,0.000000,0.000000,0.000000,0.000000,0.000000
16596,0.999940,0.750,0.000000,0.000345,0.000000,0.000000,0.000000
16597,1.000000,0.575,0.000241,0.000000,0.000000,0.000000,0.000000

**Robust Scaling**

In [27]:
from sklearn.preprocessing import RobustScaler

df8=df.copy()
scaler = RobustScaler()


df_numeric_scaled = pd.DataFrame(scaler.fit_transform(df8.select_dtypes(include=np.number)), columns=df8.select_dtypes(include=np.number).columns)
df_numeric_scaled

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,-1.000121,-0.142857,172.541667,263.636364,94.25,211.25,201.390244
1,-1.000000,-3.142857,120.833333,32.363636,170.25,19.00,97.731707
2,-0.999879,0.142857,65.708333,116.909091,94.75,82.50,86.951220
3,-0.999759,0.285714,65.291667,99.909091,82.00,73.75,80.073171
4,-0.999638,-1.571429,46.625000,80.636364,255.50,24.75,76.097561
...,...,...,...,...,...,...,...
16593,0.999638,-0.714286,-0.291667,-0.181818,0.00,-0.25,-0.390244
16594,0.999759,-0.571429,-0.291667,-0.181818,0.00,-0.25,-0.390244
16595,0.999879,0.142857,-0.333333,-0.181818,0.00,-0.25,-0.390244
16596,1.000000,0.428571,-0.333333,-0.090909,0.00,-0.25,-0.390244
16597,1.000121,-0.571429,-0.291667,-0.181818,0.00,-0.25,-0.390244